### ISSUE TITLE
argument must be a clean package path

### ISSUE THREAD

**Issue by rootbakar** [channyein1337/jsleak#1]
go: github.com/channyein1337/jsleak/@latest: argument must be a clean package path

Hi any suggestion for solve it..?

**Comment by aravindb26** [comment]
me too have same issue

**Comment by suvendu-dash** [comment]
`go get github.com/channyein1337/jsleak`

This command helped me to resolve this issue.

**Comment by channyein1337** [comment]
Looks like you are using older version of golang. You can use the above command which was provided by @suvendu-dash or you can install the latest version of golang https://go.dev/doc/install . That would solve the error.

Thanks for using it.
