### ISSUE TITLE
Not going through links

### ISSUE THREAD

**Issue by jaikishantulswani** [channyein1337/jsleak#3]
@channyein1337 It is not going through every link it found for grepping secrets.

**Comment by channyein1337** [comment]
Hello @jaikishantulswani ,

Yes it would not crawl every link. Only the link that you provided will be crawl. So you have to gather links from other tools like gospider, katana , gau or waybackurls. Then you can use jsleak with pipe. I hope this will help you to resolve the issue.

**Comment by jaikishantulswani** [comment]
@channyein1337 It would be good if it also scan the link for secrets like the below so this one single tool can work for both.


```
echo "https://example.com" |  jsleak -e -s  
Found link: [https://example.com/js/testing.js] in [https://example.com]
```

**Comment by channyein1337** [comment]
Hello @jaikishantulswani ,

Thanks for the advice. I can do that will add it in todo list and will release in soon. Also please let me know if there is any feature that will be useful.

Thanks!
